### ISSUE TITLE
Library interface is really verbose to use

### ISSUE THREAD

**Issue by LordAro** [onox/json-ada#6]
I'm trying not to be too demanding in writing this, but after spending most of day trying to use this library I really feel like the interface for this library could really do with some work.

The required Allocator makes JSON_Values really difficult to deal with, forcing you to either pass the Allocator around with the JSON_Value in some sort of record, or do everything with the JSON_Value in the same subprogram

The following is the best I can come up with for taking a filepath, reading its contents as JSON and doing something with it: (partially cribbed from the tests, as you can probably tell)

```ada
declare
   filepath : constant String := "foobar.txt";
   fd       : Ada.Streams.Stream_IO.File_Type;
   fd_size  : Ada.Streams.Stream_IO.Count;
   stream   : Ada.Streams.Stream_IO.Stream_Access;
begin
   Ada.Streams.Stream_IO.Open (fd, Ada.Streams.Stream_IO.In_File, filepath);
   fd_size := Ada.Streams.Stream_IO.Size (fd);
   stream := Ada.Streams.Stream_IO.Stream (fd);

   declare
      package JSON_Types is new JSON.Types (Integer, Float);
      package JSON_Parsers is new JSON.Parsers (JSON_Types);

      type Stream_Element_Array_Access is access Ada.Streams.Stream_Element_Array;
      procedure Free is new Ada.Unchecked_Deallocation
        (Object => Ada.Streams.Stream_Element_Array, Name => Stream_Element_Array_Access);
      subtype Byte_Array is Ada.Streams.Stream_Element_Array (1 .. Ada.Streams.Stream_Element_Offset (fd_size));

      bytes : Stream_Element_Array_Access;
   begin
      bytes := new Byte_Array;
      Byte_Array'Read (stream, bytes.all);

      declare
         json_stream    : JSON.Streams.Stream'Class := JSON.Streams.Create_Stream (bytes);
         json_allocator : JSON_Types.Memory_Allocator;
         json_val       : constant JSON_Types.JSON_Value := JSON_Parsers.Parse (json_stream, json_allocator);
      begin
         ---------------------------------
         -- do stuff with json_val here --
         ---------------------------------
      end;
      Free (bytes);
   end;
   Ada.Streams.Stream_IO.Close (fd);
end;
```

For a block that doesn't actually do anything, it's a lot of code.

I've tried making a helper function for this, that takes a callback that takes the JSON_Value as a parameter, but then due to `subprogram must not be deeper than access type` errors from GNAT, the callback can't be nested within the calling function and has to add a load of global state to the package to get any data out of the JSON_Value, which I'm not comfortable with.

Why is there a separate Allocator object? In nearly all usecases I can think of, it's only ever going to be used for a single JSON_Value. Why not just make it part of JSON_Value? (this is more or less what GNATCOLL.JSON does, I believe)

Am I missing something, or is this just how it is? Please feel free to tell me that I'm doing everything entirely wrong, I'm open to other solutions.

**Comment by onox** [comment]
Hi @LordAro, thanks for opening this issue. So it looks like you have 2 problems with the library: (1) having to keep the `Stream'Class` and `Memory_Allocator` object in scope and (2) that you need to read the contents of a file yourself.

I wrote this library to parse large JSON files (multiple MB) inside glTF models for my game engine. The library was designed to be as small as possible and let other code deal with retrieving the data. (The engine can read data from the file system as well as from .zip files, it's all abstracted behind an interface) But your issue indicates that maybe it's good to add some code to do this for you so it's easier for people to get started.

About the second issue: The `Stream'Class` object is needed because the `JSON_Value` object contains a pointer to it, the offset in the string, and the lenght of the string. This avoids having to copy any strings. The `Memory_Allocator` object is needed to store arrays and objects (key-value pairs). Currently `JSON_Value` contains raw non-null pointers to these objects.

It's indeed not nice that you have to do extra work to keep these 2 objects in memory.  I'll see if I can make use of controlled objects  (RAII) so that you don't manually have to take of them anymore.

- [x] Add a function that uses `Ada.Stream.Stream_IO` to read the content of a file
- [ ] Hide `Memory_Allocator` and possibly `Stream'Class`

**Comment by onox** [comment]
I have tried to make use of controlled objects, but that slowed down the parsing a lot. I have compared the performance with GNATCOLL.JSON, and that library seems to be 4-5x slower for large JSON files.

I have added a function to read the content of a file and simplified package `Parsers` a little bit, but you still need to keep some objects in memory.

The library was really meant to process some .json file, put everything in binary data structures, and then throw away the JSON_Value. If doing everything with the JSON_Value in a single subprogram doesn't work for you, then you might have more luck with [v2.0.0](https://github.com/onox/json-ada/releases/tag/v2.0.0) of the library.
