### ISSUE TITLE
Add a Key function for Cursors

### ISSUE THREAD

**Issue by ghost** [onox/json-ada#9]
Hello!
I noticed that the cursor type doesn't have any key function.  
Could you make a `Key` function for it, please? It would be very useful to know what each iterated value is referencing to.  
Unless you already have done that. In that case, I apologize for my oversight.

**Comment by ghost** [comment]
I just noticed that keys are actually accessible through the Value function, so it's possible, but the way to do it was quite unexpected!
Sorry for nagging you :P

**Comment by onox** [comment]
No worries :slightly_smiling_face:

The `Iterator_Element` aspect specifies that each variable in the loop is a `JSON_Value`. This is because you can iterate over the values of an array as well as the keys of an object. Keys are always strings, but JSON values of an array can be anything, and because the aspect wants 1 type, it had to be `JSON_Value`.
